namespace RealWeatherSync.Localization
{
    /// <summary>
    /// Locale ids for the strings the mod builds at runtime (status lines and the
    /// diagnostics block). Option labels and descriptions do not appear here -
    /// those ids are generated by ModSetting.GetOption*LocaleID.
    /// </summary>
    public static class LocaleKeys
    {
        /// <summary>Shared prefix; LocaleSource builds ids from it for the "key." slots.</summary>
        public const string Prefix = "RealWeatherSync.";

        public const string StatusDisabled = Prefix + "Status.Disabled";
        public const string StatusCityNotConfigured = Prefix + "Status.CityNotConfigured";
        public const string StatusResolvingLocation = Prefix + "Status.ResolvingLocation";
        public const string StatusRefreshing = Prefix + "Status.Refreshing";
        public const string StatusConnected = Prefix + "Status.Connected";
        public const string StatusCandidatesReady = Prefix + "Status.CandidatesReady";
        public const string StatusOffline = Prefix + "Status.Offline";
        public const string StatusErrorResolvingCity = Prefix + "Status.ErrorResolvingCity";
        public const string StatusIncompatibleMod = Prefix + "Status.IncompatibleMod";
        public const string StatusReleased = Prefix + "Status.Released";
        public const string StatusWaitingForGame = Prefix + "Status.WaitingForGame";

        public const string LocationNotResolved = Prefix + "Location.NotResolved";

        public const string LastUpdateNever = Prefix + "LastUpdate.Never";
        public const string LastUpdateJustNow = Prefix + "LastUpdate.JustNow";
        public const string LastUpdateMinutesAgo = Prefix + "LastUpdate.MinutesAgo";

        public const string WeatherNoData = Prefix + "Weather.NoData";
        public const string WeatherObserved = Prefix + "Weather.Observed";
        public const string WeatherApplied = Prefix + "Weather.Applied";
        public const string WeatherClouds = Prefix + "Weather.Clouds";
        public const string WeatherPrecipitation = Prefix + "Weather.Precipitation";
        public const string WeatherSnow = Prefix + "Weather.Snow";
        public const string WeatherCode = Prefix + "Weather.Code";
        public const string WeatherVisibility = Prefix + "Weather.Visibility";
        public const string WeatherFog = Prefix + "Weather.Fog";
        public const string WeatherConditions = Prefix + "Weather.Conditions";
        public const string WeatherTimeShiftPast = Prefix + "Weather.TimeShiftPast";
        public const string WeatherTimeShiftFuture = Prefix + "Weather.TimeShiftFuture";
        public const string WeatherOppositeDay = Prefix + "Weather.OppositeDay";
        public const string WeatherAntipode = Prefix + "Weather.Antipode";

        public const string SearchNoResults = Prefix + "Search.NoResults";
        public const string SearchPickOne = Prefix + "Search.PickOne";
        public const string FavouritesEmpty = Prefix + "Favourites.Empty";

        public const string OverridesActive = Prefix + "Overrides.Active";
        public const string OverridesInactive = Prefix + "Overrides.Inactive";

        public const string ErrorCityNotFound = Prefix + "Error.CityNotFound";
        public const string ErrorEmptyCity = Prefix + "Error.EmptyCity";
        public const string ErrorNetwork = Prefix + "Error.Network";
        public const string ErrorRateLimited = Prefix + "Error.RateLimited";

        public const string AboutText = Prefix + "About.Text";
        public const string SimulationImpactNote = Prefix + "About.SimulationImpact";
    }
}
